// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/398bd742115e2b071ab3edf8b543b6df6fa62dc2/cordova-ionic/cordova-ionic.d.ts
interface CordovaPlugins {
  Keyboard:Ionic.Keyboard;
}
